# COMMON CONFIGURATION FOR ALL PROFILES
debug: false
trace: false

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG

spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          name: demo-api-local
          management-base-url: http://localhost:${server.port}/
          service-base-url: ${spring.boot.admin.client.instance.management-base-url}
        enabled: false

admin-password: admin
user-password: password